<a href="https://colab.research.google.com/github/Harshad-Singh-Rathore/Data-Scientist-Assignment/blob/main/DS_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [296]:
import numpy as np
import pandas as pd

Task 1: Pick 10 locations from 5 terrain types (2 locations from each terrain)

In [297]:
df_coastal_1 = pd.read_csv('Coastal_1_SouthCarolina.csv')
df_coastal_2 = pd.read_csv('Coastal_2_NewWhales.csv')
df_desert_1 = pd.read_csv('Desert_1_Texas.csv')
df_desert_2 = pd.read_csv('Desert_2_Sud.csv')
df_mountain_1 = pd.read_csv('Mountain_1_Wisconsin.csv')
df_mountain_2 = pd.read_csv('Mountain_2_NorthDakota.csv')
df_plain_1 = pd.read_csv('Plain_1_Mississippi.csv')
df_plain_2 = pd.read_csv('Plain_2_Salzburg.csv')
df_tropical_1 = pd.read_csv('Tropical_1_SaoPaulo.csv')
df_tropical_2 = pd.read_csv('Tropical_2_Florida.csv')

In [298]:
df_coastal_1['location'] = 'South Carolina'
df_coastal_2['location'] = 'New Whales'
df_desert_1['location'] = 'Texas'
df_desert_2['location'] = 'Sud'
df_mountain_1['location'] = 'Wisconsin'
df_mountain_2['location'] = 'North Dakota'
df_plain_1['location'] = 'Mississippi'
df_plain_2['location'] = 'Salzburg'
df_tropical_1['location'] = 'Sao Paulo'
df_tropical_2['location'] = 'Florida'

In [299]:
df_coastal_1['terrain'] = 'Coastal'
df_coastal_2['terrain'] = 'Coastal'
df_desert_1['terrain'] = 'Desert'
df_desert_2['terrain'] = 'Desert'
df_mountain_1['terrain'] = 'Mountain'
df_mountain_2['terrain'] = 'Mountain'
df_plain_1['terrain'] = 'Plain'
df_plain_2['terrain'] = 'Plain'
df_tropical_1['terrain'] = 'Tropical'
df_tropical_2['terrain'] = 'Tropical'

In [300]:
df_all_predicted = pd.concat([df_coastal_1, df_coastal_2, df_desert_1, df_desert_2, df_mountain_1, df_mountain_2, df_plain_1, df_plain_2, df_tropical_1, df_tropical_2], ignore_index=True)

In [301]:
df_all_predicted.head()

,time,wind_speed_predicted,wind_direction_predicted,location,terrain
0,2025-01-01T00:00,3.67,191,South Carolina,Coastal
1,2025-01-01T01:00,3.59,193,South Carolina,Coastal
2,2025-01-01T02:00,3.40,208,South Carolina,Coastal
3,2025-01-01T03:00,3.58,210,South Carolina,Coastal
4,2025-01-01T04:00,4.03,226,South Carolina,Coastal

In [302]:
df_coastal_1_actual = pd.read_csv('Coastal_1_SouthCarolina_actual.csv')
df_coastal_2_actual = pd.read_csv('Coastal_2_NewWhales_actual.csv')
df_desert_1_actual = pd.read_csv('Desert_1_Texas_actual.csv')
df_desert_2_actual = pd.read_csv('Desert_2_Sud_actual.csv')
df_mountain_1_actual = pd.read_csv('Mountain_1_Wisconsin_actual.csv')
df_mountain_2_actual = pd.read_csv('Mountain_2_NorthDakota_actual.csv')
df_plain_1_actual = pd.read_csv('Plain_1_Mississippi_actual.csv')
df_plain_2_actual = pd.read_csv('Plain_2_Salzburg_actual.csv')
df_tropical_1_actual = pd.read_csv('Tropical_1_SaoPaulo_actual.csv')
df_tropical_2_actual = pd.read_csv('Tropical_2_Florida_actual.csv')

In [303]:
df_coastal_1_actual['location'] = 'South Carolina'
df_coastal_2_actual['location'] = 'New Whales'
df_desert_1_actual['location'] = 'Texas'
df_desert_2_actual['location'] = 'Sud'
df_mountain_1_actual['location'] = 'Wisconsin'
df_mountain_2_actual['location'] = 'North Dakota'
df_plain_1_actual['location'] = 'Mississippi'
df_plain_2_actual['location'] = 'Salzburg'
df_tropical_1_actual['location'] = 'Sao Paulo'
df_tropical_2_actual['location'] = 'Florida'

In [304]:
df_coastal_1_actual['terrain'] = 'Coastal'
df_coastal_2_actual['terrain'] = 'Coastal'
df_desert_1_actual['terrain'] = 'Desert'
df_desert_2_actual['terrain'] = 'Desert'
df_mountain_1_actual['terrain'] = 'Mountain'
df_mountain_2_actual['terrain'] = 'Mountain'
df_plain_1_actual['terrain'] = 'Plain'
df_plain_2_actual['terrain'] = 'Plain'
df_tropical_1_actual['terrain'] = 'Tropical'
df_tropical_2_actual['terrain'] = 'Tropical'

In [305]:
df_all_actual = pd.concat([df_coastal_1_actual, df_coastal_2_actual, df_desert_1_actual, df_desert_2_actual, df_mountain_1_actual, df_mountain_2_actual, df_plain_1_actual, df_plain_2_actual, df_tropical_1_actual, df_tropical_2_actual], ignore_index=True)

In [306]:
df_all_actual.head()

,time,wind_speed_actual,wind_direction_actual,location,terrain
0,2025-01-01T00:00,4.32,207,South Carolina,Coastal
1,2025-01-01T01:00,4.25,217,South Carolina,Coastal
2,2025-01-01T02:00,4.62,219,South Carolina,Coastal
3,2025-01-01T03:00,5.32,229,South Carolina,Coastal
4,2025-01-01T04:00,5.48,249,South Carolina,Coastal

Task 2: Merge both the APIs

In [307]:
df_all = pd.merge(
    df_all_predicted,
    df_all_actual,
    on=['time', 'location', 'terrain'],
    how='inner'
)

In [308]:
df_all.head()

,time,wind_speed_predicted,wind_direction_predicted,location,terrain,wind_speed_actual,wind_direction_actual
0,2025-01-01T00:00,3.67,191,South Carolina,Coastal,4.32,207
1,2025-01-01T01:00,3.59,193,South Carolina,Coastal,4.25,217
2,2025-01-01T02:00,3.40,208,South Carolina,Coastal,4.62,219
3,2025-01-01T03:00,3.58,210,South Carolina,Coastal,5.32,229
4,2025-01-01T04:00,4.03,226,South Carolina,Coastal,5.48,249

In [309]:
df_all['time'] = pd.to_datetime(df_all['time'])

In [327]:
df_all['bias'] = df_all['wind_speed_actual'] - df_all['wind_speed_predicted']

In [311]:
df_all['hour'] = df_all['time'].dt.hour
df_all['month'] = df_all['time'].dt.month

In [312]:
df_all['wind_dir_sin'] = np.sin(np.radians(df_all['wind_direction_predicted']))
df_all['wind_dir_cos'] = np.cos(np.radians(df_all['wind_direction_predicted']))

In [313]:
df_analysis = df_all.copy()

In [314]:
df_all = pd.get_dummies(
    df_all,
    columns=['location', 'terrain'],
    drop_first=True
)

Task 3: Split the data

In [328]:
train = df_all[df_all['time'] < '2025-11-01']  # Jan-Oct
test  = df_all[df_all['time'] >= '2025-11-01'] # Nov-Dec

Task 4: Build a correction model

In [329]:
# Feature Selection
features = [col for col in df_all.columns if col not in [
    'time',
    'wind_speed_actual',
    'bias'
]]

In [330]:
X_train = train[features]
y_train = train['bias']

X_test = test[features]
y_test = test['bias']

In [331]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
from xgboost import XGBRegressor

In [319]:
# Model Training
model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [320]:
bias_pred = model.predict(X_test)

test['corrected_wind'] = (
    test['wind_speed_predicted'] + bias_pred
)

/tmp/ipykernel_8115/2490665206.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['corrected_wind'] = (

Task 5: Evaluation on the test set

In [321]:
#RMSE
rmse_raw = np.sqrt(mean_squared_error(
    test['wind_speed_actual'],
    test['wind_speed_predicted']
))

rmse_corrected = np.sqrt(mean_squared_error(
    test['wind_speed_actual'],
    test['corrected_wind']
))

print(f'RMSE before correction: {rmse_raw}')
print(f'RMSE after correction: {rmse_corrected}')

RMSE before correction: 1.123254498944432
RMSE after correction: 0.821173369684327

In [322]:
# Mean Absolute Error
mae = mean_absolute_error(
    test['wind_speed_actual'],
    test['corrected_wind']
)
mae

0.6344832361369807

In [323]:
# Bias
bias = (test['corrected_wind'] - test['wind_speed_actual']).mean()
bias

np.float64(0.07494493502773909)

Task 6: Analysis

In [324]:
# Terrain Bias
terrain_bias = df_analysis.groupby('terrain')['bias'].mean()
terrain_bias

terrain
Coastal     0.225680
Desert     -0.400638
Mountain    0.034557
Plain       0.339503
Tropical    0.250467
Name: bias, dtype: float64

In [325]:
# Temporal Analysis
hourly_bias = df_analysis.groupby('hour')['bias'].mean()
hourly_bias

hour
0     0.002581
1     0.197710
2     0.270904
3     0.300866
4     0.332386
5     0.357575
6     0.326701
7     0.312132
8     0.315200
9     0.330348
10    0.325052
11    0.331896
12    0.318173
13    0.214663
14   -0.003378
15   -0.143559
16   -0.222079
17   -0.248992
18   -0.255332
19   -0.256745
20   -0.215945
21   -0.197485
22   -0.110534
23   -0.124197
Name: bias, dtype: float64

In [326]:
monthly_bias = df_analysis.groupby('month')['bias'].mean()
monthly_bias

month
1     0.151684
2    -0.002095
3     0.051638
4     0.056836
5     0.000531
6     0.001511
7     0.100909
8     0.131028
9     0.051143
10    0.155292
11    0.232125
12    0.138882
Name: bias, dtype: float64